# -*- coding: utf-8 -*-
"""streamlitfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDXUPCTLqVDx-9SYFKOvOgiRwKfcw2j8
"""

import streamlit as st


st.title("Environmental Econ Final Project")

st.header("USA Case Study")
import stream_enveconindividual

st.header("Portugal Case Study")
import stream_envecongroup